Update release-apim-helm-chart.yaml

diff --git a/.github/workflows/release-apim-helm-chart.yaml b/.github/workflows/release-apim-helm-chart.yaml
--- a/.github/workflows/release-apim-helm-chart.yaml
+++ b/.github/workflows/release-apim-helm-chart.yaml
@@ -20,19 +20,19 @@ jobs:
     - name: Get release version
       run: |
         echo "Get version number from Release-Tag: ${{ github.event.release.tag_name }}"
-        RELEASE_VERSION=`echo "${{ github.event.release.tag_name }}" | gawk 'match($0, /.*([0-9].*\.[0-9]\.[0-9].*[-A-Za-z]*)/, matches) {print matches[1]}'`
-        if [ -z ${RELEASE_VERSION} ]; then echo "Could not extrast release version from tag: ${{ github.event.release.tag_name }}"; exit 99; fi
+        RELEASE_VERSION=`echo "${{ github.event.release.tag_name }}" | gawk 'match($0, /.*([0-9]*\.[0-9]*\.[0-9]*[-A-Za-z]*)/, matches) {print matches[1]}'`
+        if [ -z ${RELEASE_VERSION} ]; then echo "Could not extract release version from tag: ${{ github.event.release.tag_name }}"; exit 99; fi
         echo "Release version is: $RELEASE_VERSION"
         echo RELEASE_VERSION=$RELEASE_VERSION >> $GITHUB_ENV
     - name: Set version number
       run: |
         yq -i '.version="${{ env.RELEASE_VERSION }}"' ./Chart.yaml
         echo "Set version: ${{ env.RELEASE_VERSION }} in AWS-EKS Example Readme."
-        sed -E -i 's/(apim-helm)-[0-9].*\.[0-9].*\.[0-9].*/\1-${{ env.RELEASE_VERSION }}/' ./examples/aws-eks/README.md
-        sed -E -i 's/(helm-chart-axway-apim)-[0-9].*\.[0-9].*\.[0-9].*(\.tgz)/\1-${{ env.RELEASE_VERSION }}\2/' ./examples/aws-eks/README.md
+        sed -E -i 's/(apim-helm)-[0-9]*\.[0-9]*\.[0-9]*/\1-${{ env.RELEASE_VERSION }}/' ./examples/aws-eks/README.md
+        sed -E -i 's/(helm-chart-axway-apim)-[0-9]*\.[0-9]*\.[0-9]*(\.tgz)/\1-${{ env.RELEASE_VERSION }}\2/' ./examples/aws-eks/README.md
         echo "Set version: ${{ env.RELEASE_VERSION }} in Azure Example Readme."
-        sed -E -i 's/(apim-helm)-[0-9].*\.[0-9].*\.[0-9].*/\1-${{ env.RELEASE_VERSION }}/' ./examples/azure-aks/README.md
-        sed -E -i 's/(helm-chart-axway-apim)-[0-9].*\.[0-9].*\.[0-9].*(\.tgz)/\1-${{ env.RELEASE_VERSION }}\2/' ./examples/azure-aks/README.md
+        sed -E -i 's/(apim-helm)-[0-9]*\.[0-9]*\.[0-9]*/\1-${{ env.RELEASE_VERSION }}/' ./examples/azure-aks/README.md
+        sed -E -i 's/(helm-chart-axway-apim)-[0-9]*\.[0-9]*\.[0-9]*(\.tgz)/\1-${{ env.RELEASE_VERSION }}\2/' ./examples/azure-aks/README.md
         cat ./Chart.yaml
     - name: Create packaged Helm-Chart
       run: |
