Update release-apim-helm-chart.yaml

diff --git a/.github/workflows/release-apim-helm-chart.yaml b/.github/workflows/release-apim-helm-chart.yaml
--- a/.github/workflows/release-apim-helm-chart.yaml
+++ b/.github/workflows/release-apim-helm-chart.yaml
@@ -21,7 +21,7 @@ jobs:
       run: |
         echo "Get version number from Release-Tag: ${{ github.event.release.tag_name }}"
         RELEASE_VERSION=`echo "${{ github.event.release.tag_name }}" | gawk 'match($0, /.*([0-9].*\.[0-9]\.[0-9].*[-A-Za-z]*)/, matches) {print matches[1]}'`
-        if [ -z ${RELEASE_VERSION} ]; then; echo "Could not extrast release version from tag: ${{ github.event.release.tag_name }}"; exit 99; fi;
+        if [ -z ${RELEASE_VERSION} ]; then echo "Could not extrast release version from tag: ${{ github.event.release.tag_name }}"; exit 99; fi
         echo "Release version is: $RELEASE_VERSION"
         echo RELEASE_VERSION=$RELEASE_VERSION >> $GITHUB_ENV
     - name: Set version number
